default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  wkhtmltopdf_binary: C:\Ruby193\wkhtmltopdf\bin\wkhtmltopdf.exe

test:
  <<: *default

production: &deploy
  <<: *default
  wkhtmltopdf_binary: /app/.apt/usr/local/bin/wkhtmltopdf

staging:
  <<: *deploy
